In [11]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

import sys
import os

sys.path.append(os.path.abspath("../Src"))

from log.utils.logger import setup_logger

In [12]:
logger = setup_logger("08_Normalise")
logger.info("Starting normalization pipeline...")

2026-06-24 22:06:57 | INFO | Starting normalization pipeline...

In [13]:
master = pd.read_csv("../Data/Processed/final_master_dataset.csv")

logger.info(f"Dataset loaded: {master.shape}")

2026-06-24 22:06:57 | INFO | Dataset loaded: (36551, 29)

In [14]:
master.head()

,date,player_name,acwr,atl,ctl28,ctl42,daily_load,monotony,strain,weekly_load,...,defensive_performance,avg_speed,max_speed,avg_heart_rate,max_heart_rate,avg_accel_x,avg_accel_y,avg_accel_z,rows,injured
0,2020-01-01,TeamA-0362cdd5-7a63-480a-a46a-62a99fb1692f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-01,TeamA-2d44f941-2f24-4fc2-afa8-611a091f2e93,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-01,TeamA-32fed4b3-d7fc-482d-ba21-c46c58f015b5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-01,TeamA-358603ef-b3a3-46b5-b80a-ad64e06b6592,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-01,TeamA-3e5f6e2b-46b7-4890-84a9-3bbb2649af5a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
master.info()

<class 'pandas.DataFrame'>
RangeIndex: 36551 entries, 0 to 36550
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   36551 non-null  str
 1   player_name            36551 non-null  str
 2   acwr                   36551 non-null  float64
 3   atl                    36551 non-null  float64
 4   ctl28                  36551 non-null  float64
 5   ctl42                  36551 non-null  float64
 6   daily_load             36551 non-null  float64
 7   monotony               36551 non-null  float64
 8   strain                 36551 non-null  float64
 9   weekly_load            36551 non-null  float64
 10  fatigue                16993 non-null  float64
 11  mood                   17000 non-null  float64
 12  readiness              16998 non-null  float64
 13  sleep_duration         16982 non-null  float64
 14  sleep_quality          16995 non-null  float64
 15  soreness               17000 non-null  float64
 16  stress                 16998 non-null  float64
 17  team_performance       248 non-null    float64
 18  offensive_performance  248 non-null    float64
 19  defensive_performance  248 non-null    float64
 20  avg_speed              1785 non-null   float64
 21  max_speed              1785 non-null   float64
 22  avg_heart_rate         1785 non-null   float64
 23  max_heart_rate         1785 non-null   float64
 24  avg_accel_x            1785 non-null   float64
 25  avg_accel_y            1785 non-null   float64
 26  avg_accel_z            1785 non-null   float64
 27  rows                   1785 non-null   float64
 28  injured                1785 non-null   float64
dtypes: float64(27), str(2)
memory usage: 9.9 MB

In [16]:
master.select_dtypes(include="number").columns

Index(['acwr', 'atl', 'ctl28', 'ctl42', 'daily_load', 'monotony', 'strain',
       'weekly_load', 'fatigue', 'mood', 'readiness', 'sleep_duration',
       'sleep_quality', 'soreness', 'stress', 'team_performance',
       'offensive_performance', 'defensive_performance', 'avg_speed',
       'max_speed', 'avg_heart_rate', 'max_heart_rate', 'avg_accel_x',
       'avg_accel_y', 'avg_accel_z', 'rows', 'injured'],
      dtype='str')

In [19]:
continuous_columns = [
    "acwr",
    "atl",
    "ctl28",
    "ctl42",
    "daily_load",
    "monotony",
    "strain",
    "weekly_load",
    "fatigue",
    "mood",
    "readiness",
    "sleep_duration",
    "sleep_quality",
    "soreness",
    "stress",
    "avg_speed",
    "max_speed",
    "avg_heart_rate",
    "max_heart_rate",
    "avg_accel_x",
    "avg_accel_y",
    "avg_accel_z",
    "rows"
]

In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
scaler = StandardScaler()

master[continuous_columns] = scaler.fit_transform(
    master[continuous_columns]
)

In [22]:
master[continuous_columns].head()

,acwr,atl,ctl28,ctl42,daily_load,monotony,strain,weekly_load,fatigue,mood,...,soreness,stress,avg_speed,max_speed,avg_heart_rate,max_heart_rate,avg_accel_x,avg_accel_y,avg_accel_z,rows
0,-0.864924,-0.973828,-1.061103,-1.085104,-0.652444,-0.963435,-0.769726,-0.973523,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.864924,-0.973828,-1.061103,-1.085104,-0.652444,-0.963435,-0.769726,-0.973523,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-0.864924,-0.973828,-1.061103,-1.085104,-0.652444,-0.963435,-0.769726,-0.973523,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-0.864924,-0.973828,-1.061103,-1.085104,-0.652444,-0.963435,-0.769726,-0.973523,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-0.864924,-0.973828,-1.061103,-1.085104,-0.652444,-0.963435,-0.769726,-0.973523,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
master.to_csv(
    "../Data/Processed/final_master_dataset_normalized.csv",
    index=False
)