In [1]:
!pip install pandas pyarrow fastparquet

Collecting pandas
  Using cached pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting pyarrow
  Using cached pyarrow-24.0.0-cp312-cp312-win_amd64.whl.metadata (3.0 kB)
Collecting fastparquet
  Using cached fastparquet-2026.5.0-cp312-cp312-win_amd64.whl.metadata (4.9 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.4.6-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\practicum project\practicum\venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting cramjam>=2.3 (from fastparquet)
  Using cached cramjam-2.11.0-cp312-cp312-win_amd64.whl.metadata (681 bytes)
Collecting fsspec (from fastparquet)
  Using cached fsspec-2026.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: packaging in e:\practicum project\practicum\venv\lib\site-packages (from fastparquet) (26.2)
Requirement already satisfied: six>=1.5 in e:\practicum project\practicum\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.3-cp312-cp312-win_amd64.whl (9.8 MB)
Using cached pyarrow-24.0.0-cp312-cp312-win_amd64.whl (27.4 MB)
Using cached fastparquet-2026.5.0-cp312-cp312-win_amd64.whl (695 kB)
Using cached cramjam-2.11.0-cp312-cp312-win_amd64.whl (1.7 MB)
Using cached numpy-2.4.6-cp312-cp312-win_amd64.whl (12.3 MB)
Using cached fsspec-2026.4.0-py3-none-any.whl (203 kB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, pyarrow, numpy, fsspec, cramjam, pandas, fastparquet
Successfully installed cramjam-2.11.0 fastparquet-2026.5.0 fsspec-2026.4.0 numpy-2.4.6 pandas-3.0.3 pyarrow-24.0.0 tzdata-2026.2

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

CHECKING COLUMNS OF SUBJECTIVE FILE

In [14]:

df_game_performance = pd.read_csv("../Data/subjective/game-performance/game-performance.csv")

df_game_performance.head()

,player_name,team_performance,offensive_performance,defensive_performance,timestamp
0,TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6,7,5,6,11.07.2020
1,TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6,7,7,7,07.10.2020
2,TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6,5,7,5,18.10.2020
3,TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6,6,6,7,31.10.2020
4,TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6,4,4,4,07.11.2020

In [15]:

df_fatigue = pd.read_csv("../Data/subjective/wellness/fatigue.csv")
df_fatigue.head()

,Fatigue Data,TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6,TeamA-b58af410-da77-479e-b93c-e03617b9f36d,TeamA-5cd7a61b-88b2-46d2-94f8-5a0d4f682d93,TeamA-74afe68c-f348-414c-9754-6d6f9df12587,TeamA-bcc03f81-2733-45d3-abf1-f7a709c63e68,TeamA-2d44f941-2f24-4fc2-afa8-611a091f2e93,TeamA-ecdbd8ec-61a7-4131-97ec-3af76f621f65,TeamA-e920ae60-5c4b-4597-be27-fc6876dcec33,TeamA-af719df9-3e6c-4ad4-9e8e-0c0c45f4f76a,...,TeamB-9c845827-99f9-47f4-977d-2200a107a013,TeamB-ab5ec6e5-b0f3-401e-8dc5-aa6c5070e255,TeamB-d9501f3a-aaa1-4311-8b8b-3a8d3f21480f,TeamB-5eba590a-cecb-400f-a92e-08224c7e2e59,TeamB-7d41e602-eece-328b-ff7b-118e820865d6,TeamB-4b1e23d2-4204-4e16-9991-e0490649079b,TeamB-e1f63352-01cb-4688-9486-5c6f1e5cf0cd,TeamB-5a921187-19c7-8df4-8f4f-f31e78de5857,TeamB-6d568bee-175f-4dcb-9d3a-0f3e8f35de07,TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3
0,01.01.2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,02.01.2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,03.01.2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,04.01.2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,05.01.2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_acwr = pd.read_csv("../Data/subjective/training-load/acwr.csv")
df_acwr.head()

,Date,TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6,TeamA-b58af410-da77-479e-b93c-e03617b9f36d,TeamA-5cd7a61b-88b2-46d2-94f8-5a0d4f682d93,TeamA-74afe68c-f348-414c-9754-6d6f9df12587,TeamA-bcc03f81-2733-45d3-abf1-f7a709c63e68,TeamA-2d44f941-2f24-4fc2-afa8-611a091f2e93,TeamA-ecdbd8ec-61a7-4131-97ec-3af76f621f65,TeamA-e920ae60-5c4b-4597-be27-fc6876dcec33,TeamA-af719df9-3e6c-4ad4-9e8e-0c0c45f4f76a,...,TeamB-9c845827-99f9-47f4-977d-2200a107a013,TeamB-ab5ec6e5-b0f3-401e-8dc5-aa6c5070e255,TeamB-d9501f3a-aaa1-4311-8b8b-3a8d3f21480f,TeamB-5eba590a-cecb-400f-a92e-08224c7e2e59,TeamB-7d41e602-eece-328b-ff7b-118e820865d6,TeamB-4b1e23d2-4204-4e16-9991-e0490649079b,TeamB-e1f63352-01cb-4688-9486-5c6f1e5cf0cd,TeamB-5a921187-19c7-8df4-8f4f-f31e78de5857,TeamB-6d568bee-175f-4dcb-9d3a-0f3e8f35de07,TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3
0,01.01.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,02.01.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,03.01.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,04.01.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,05.01.2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Phase 2 - Data Integration